spring:
  datasource:
    url: jdbc:mysql://26.201.192.85:3306/acm?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: fangyi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail: # smtp服务主机  qq邮箱则为smtp.qq.com  整合邮件配置
      host: smtp.163.com
      # 服务协议 smtp为发送邮件
      protocol: smtp
      # 编码集
      default-encoding: UTF-8
      # 发送邮件的账户
      username: sauerkrautttt@163.com
      # 授权码 邮箱服务器提供的授权码，不是你邮箱的密码
      password: PQhxXHBKs8ACGgHj
      # 开启一些权限
      test-connection: true
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
  mvc:
    static-path-pattern: static/**
  devtools:
    restart:
          # 开启热部署（更改文件后，自动重启）
          enabled: true
          ## 设置哪些资源变动后不触发热部署，会覆盖默认的exclude内容（资源不会触发重启，但会触发实时重新加载）
          exclude:
          ## 监控额外的路径（优先于exclude）
          additional-paths: src/main/java
          log-condition-evaluation-delta: false
  upload:
    dir: "http://26.201.192.85:8181"
server:
  port: 8181


